language: cpp
compiler:
  - clang
notifications:
  email: 
      - github@donner.at
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/juliareleases -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init();'
  - julia -e 'run(`ln -s $(pwd()) $(Pkg.dir("ExtremelyRandomizedTrees"))`); Pkg.pin("ExtremelyRandomizedTrees")'
  - julia -e 'Pkg.resolve()'
  - julia ~/.julia/v0.3/ExtremelyRandomizedTrees/test/runtests.jl
